# Generated by Django 5.1.2 on 2024-10-12 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='car_make',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_model',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='car_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_plate',
            field=models.CharField(default='Unknown', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_service_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vin_number',
            field=models.CharField(default='Unknown', max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
