# Generated by Django 5.1.2 on 2024-12-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='license_plate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vin_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
